/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "./supabase.types";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const clientStackdCertificationRowSchema = z.object({
  created_at: z.string(),
  description: z.string(),
  id: z.string(),
  image_url: z.string(),
  ranking_index: z.number(),
  title: z.string(),
  updated_at: z.string(),
});

export const clientStackdCertificationInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string(),
  id: z.string().optional(),
  image_url: z.string(),
  ranking_index: z.number(),
  title: z.string(),
  updated_at: z.string(),
});

export const clientStackdCertificationUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional(),
  id: z.string().optional(),
  image_url: z.string().optional(),
  ranking_index: z.number().optional(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
});

export const clientStackdFileRecordRowSchema = z.object({
  created_at: z.string(),
  deleted_at: z.string().nullable(),
  file_description: z.string(),
  file_name: z.string(),
  file_path: z.string(),
  id: z.string(),
  preview_url: z.string(),
  preview_url_256: z.string().nullable(),
  preview_url_512: z.string().nullable(),
  preview_url_64: z.string().nullable(),
  storage_ref: z.string(),
  storage_ref_256: z.string().nullable(),
  storage_ref_512: z.string().nullable(),
  storage_ref_64: z.string().nullable(),
  updated_at: z.string(),
});

export const clientStackdFileRecordInsertSchema = z.object({
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  file_description: z.string(),
  file_name: z.string(),
  file_path: z.string(),
  id: z.string().optional(),
  preview_url: z.string(),
  preview_url_256: z.string().optional().nullable(),
  preview_url_512: z.string().optional().nullable(),
  preview_url_64: z.string().optional().nullable(),
  storage_ref: z.string(),
  storage_ref_256: z.string().optional().nullable(),
  storage_ref_512: z.string().optional().nullable(),
  storage_ref_64: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const clientStackdFileRecordUpdateSchema = z.object({
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  file_description: z.string().optional(),
  file_name: z.string().optional(),
  file_path: z.string().optional(),
  id: z.string().optional(),
  preview_url: z.string().optional(),
  preview_url_256: z.string().optional().nullable(),
  preview_url_512: z.string().optional().nullable(),
  preview_url_64: z.string().optional().nullable(),
  storage_ref: z.string().optional(),
  storage_ref_256: z.string().optional().nullable(),
  storage_ref_512: z.string().optional().nullable(),
  storage_ref_64: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const clientStackdTeamMemberRowSchema = z.object({
  achievements: jsonSchema.nullable(),
  bio: z.string(),
  created_at: z.string(),
  first_name: z.string(),
  id: z.string(),
  image_url: z.string(),
  image_url_256: z.string().nullable(),
  image_url_512: z.string().nullable(),
  image_url_64: z.string().nullable(),
  last_name: z.string(),
  linkedinUrl: z.string().nullable(),
  middle_name: z.string().nullable(),
  ranking_index: z.number(),
  role: z.string(),
  updated_at: z.string(),
});

export const clientStackdTeamMemberInsertSchema = z.object({
  achievements: jsonSchema.optional().nullable(),
  bio: z.string(),
  created_at: z.string().optional(),
  first_name: z.string(),
  id: z.string().optional(),
  image_url: z.string(),
  image_url_256: z.string().optional().nullable(),
  image_url_512: z.string().optional().nullable(),
  image_url_64: z.string().optional().nullable(),
  last_name: z.string(),
  linkedinUrl: z.string().optional().nullable(),
  middle_name: z.string().optional().nullable(),
  ranking_index: z.number(),
  role: z.string(),
  updated_at: z.string(),
});

export const clientStackdTeamMemberUpdateSchema = z.object({
  achievements: jsonSchema.optional().nullable(),
  bio: z.string().optional(),
  created_at: z.string().optional(),
  first_name: z.string().optional(),
  id: z.string().optional(),
  image_url: z.string().optional(),
  image_url_256: z.string().optional().nullable(),
  image_url_512: z.string().optional().nullable(),
  image_url_64: z.string().optional().nullable(),
  last_name: z.string().optional(),
  linkedinUrl: z.string().optional().nullable(),
  middle_name: z.string().optional().nullable(),
  ranking_index: z.number().optional(),
  role: z.string().optional(),
  updated_at: z.string().optional(),
});

export const clientStackdTestResourceRowSchema = z.object({
  created_at: z.string(),
  description: z.string(),
  id: z.string(),
  title: z.string(),
});

export const clientStackdTestResourceInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string(),
  id: z.string().optional(),
  title: z.string(),
});

export const clientStackdTestResourceUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional(),
  id: z.string().optional(),
  title: z.string().optional(),
});

export const clientStackdTestimonialRowSchema = z.object({
  body: z.string(),
  company: z.string().nullable(),
  company_logo_url: z.string().nullable(),
  company_logo_url_256: z.string().nullable(),
  company_logo_url_512: z.string().nullable(),
  company_logo_url_64: z.string().nullable(),
  created_at: z.string(),
  id: z.string(),
  image_url: z.string(),
  image_url_256: z.string().nullable(),
  image_url_512: z.string().nullable(),
  image_url_64: z.string().nullable(),
  name: z.string(),
  ranking_index: z.number(),
  role: z.string().nullable(),
  updated_at: z.string(),
});

export const clientStackdTestimonialInsertSchema = z.object({
  body: z.string(),
  company: z.string().optional().nullable(),
  company_logo_url: z.string().optional().nullable(),
  company_logo_url_256: z.string().optional().nullable(),
  company_logo_url_512: z.string().optional().nullable(),
  company_logo_url_64: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  image_url: z.string(),
  image_url_256: z.string().optional().nullable(),
  image_url_512: z.string().optional().nullable(),
  image_url_64: z.string().optional().nullable(),
  name: z.string(),
  ranking_index: z.number(),
  role: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const clientStackdTestimonialUpdateSchema = z.object({
  body: z.string().optional(),
  company: z.string().optional().nullable(),
  company_logo_url: z.string().optional().nullable(),
  company_logo_url_256: z.string().optional().nullable(),
  company_logo_url_512: z.string().optional().nullable(),
  company_logo_url_64: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  image_url: z.string().optional(),
  image_url_256: z.string().optional().nullable(),
  image_url_512: z.string().optional().nullable(),
  image_url_64: z.string().optional().nullable(),
  name: z.string().optional(),
  ranking_index: z.number().optional(),
  role: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const clientStackdUsersRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string(),
  role: z.string(),
  updated_at: z.string().nullable(),
});

export const clientStackdUsersInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string(),
  role: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const clientStackdUsersUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  role: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const clientStackdIsAdminArgsSchema = z.never();

export const clientStackdIsAdminReturnsSchema = z.boolean();
