/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "./supabase.types";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const clientStackdTestResourceRowSchema = z.object({
  created_at: z.string(),
  description: z.string(),
  id: z.string(),
  title: z.string(),
});

export const clientStackdTestResourceInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string(),
  id: z.string().optional(),
  title: z.string(),
});

export const clientStackdTestResourceUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional(),
  id: z.string().optional(),
  title: z.string().optional(),
});
